name:         stackage-server

flags:
  library-only:
    description: Build for use with "yesod devel"
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: true

dependencies:
- base
- yesod
- aeson
- barrier
- blaze-markup
- bytestring
- classy-prelude
- classy-prelude-yesod
- conduit
- conduit-extra
- cryptonite
- directory
- email-validate
- esqueleto
- exceptions
- fast-logger
- foreign-store
- ghc-prim
- html-conduit
- http-conduit
- monad-logger
- mtl
#- prometheus-client
#- prometheus-metrics-ghc
- pantry
- path
- persistent
- persistent-template
- resourcet
- rio
- shakespeare
- tar-conduit
- template-haskell
- temporary
- text
- transformers
- these
- unliftio
- wai
- wai-extra
- wai-logger
#- wai-middleware-prometheus
- warp
- xml-conduit
- xml-types
- yaml
- yesod-auth
- yesod-core
- yesod-form
- yesod-newsfeed
- yesod-static
- zlib
- unordered-containers
- hashable
- Cabal
- mono-traversable
- time
- process
- cmark-gfm
- formatting
- blaze-html
- haddock-library
- yesod-gitrepo
- yesod-gitrev
- hoogle
- deepseq
- auto-update
- yesod-sitemap
- streaming-commons
- classy-prelude-conduit
- path-pieces
- persistent-postgresql
- filepath
- http-client
- http-types
- amazonka
- amazonka-core
- amazonka-s3
- lens
- file-embed
- resource-pool
- containers
- pretty

default-extensions:
- OverloadedStrings

library:
  source-dirs: src
  when:
  - condition: (flag(dev)) || (flag(library-only))
    then:
      ghc-options:
      - -Wall
      - -O0
      cpp-options: -DDEVELOPMENT
    else:
      ghc-options:
      - -Wall
      - -O2

executables:
  stackage-server:
    main: main.hs
    source-dirs: app
    ghc-options: -threaded -O2 -rtsopts "-with-rtsopts=-N -T"
    dependencies:
    - stackage-server
    when:
    - condition: flag(library-only)
      buildable: false
    - condition: flag(dev)
      cpp-options: -DDEVELOPMENT

  stackage-server-cron:
    main: stackage-server-cron.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -O2
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - optparse-applicative
    - rio
    - stackage-server
    when:
    - condition: flag(library-only)
      buildable: false
    - condition: flag(dev)
      cpp-options: -DDEVELOPMENT
